/* eslint-disable @typescript-eslint/no-explicit-any, jsx-a11y/alt-text */
import React from 'react';
import { Text, View } from '@react-pdf/renderer';
import { globalPDFStyles, COLORS, LAYOUT } from './globalPDFStyles';

// Types
interface PdfHeaderProps {
    title: string;
    projectName?: string;
    clientName?: string;
    producer?: string;
    date?: string;
    status?: 'Ready' | 'Empty'; // For optional vector status rendering
}

export const PdfStatusIcon = ({ status }: { status: 'Ready' | 'Empty' }) => (
    <View style={{
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: status === 'Ready' ? COLORS.emerald : COLORS.red
    }} />
);

export const PdfHeader = ({ title, projectName, clientName, producer, date, status }: PdfHeaderProps) => {
    return (
        <View style={{ marginBottom: 24 }} fixed>
            {/* Top Row: Doc Title + Date */}
            <View style={{
                flexDirection: 'row',
                justifyContent: 'space-between',
                alignItems: 'flex-end',
                borderBottomWidth: 3,
                borderBottomColor: COLORS.charcoal,
                paddingBottom: 12,
                marginBottom: 0
            }}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                    <Text style={globalPDFStyles.h1}>{title}</Text>
                    {status && <PdfStatusIcon status={status} />}
                </View>
                {date && (
                    <Text style={{ fontSize: 9, fontWeight: 700, textTransform: 'uppercase', color: COLORS.mutedText, marginBottom: 4 }}>
                        {date}
                    </Text>
                )}
            </View>

            {/* Metadata Row: Client/Project + Producer */}
            <View style={{
                flexDirection: 'row',
                justifyContent: 'space-between',
                alignItems: 'center',
                paddingVertical: 8,
                borderBottomWidth: 0.5,
                borderBottomColor: COLORS.slate
            }}>
                {/* Left: Client // Project */}
                <View style={{ flexDirection: 'row', gap: 8 }}>
                    {clientName && (
                        <Text style={{ fontSize: 8, fontWeight: 700, textTransform: 'uppercase', color: COLORS.mutedText }}>
                            {clientName} <Text style={{ color: COLORS.slate }}>{'//'}</Text>
                        </Text>
                    )}
                    <Text style={{ fontSize: 8, fontWeight: 700, textTransform: 'uppercase', color: COLORS.obsidian }}>
                        {projectName || 'UNTITLED PROJECT'}
                    </Text>
                </View>

                {/* Right: Producer */}
                {producer && (
                    <View style={{ flexDirection: 'row', gap: 8 }}>
                        <Text style={{ fontSize: 8, fontWeight: 700, textTransform: 'uppercase', color: COLORS.mutedText }}>
                            PRODUCER
                        </Text>
                        <Text style={{ fontSize: 8, fontWeight: 700, textTransform: 'uppercase', color: COLORS.obsidian }}>
                            {producer}
                        </Text>
                    </View>
                )}
            </View>
        </View>
    );
};

export const PdfFooter = () => (
    <View style={{ position: 'absolute', bottom: LAYOUT.padding, left: LAYOUT.padding, right: LAYOUT.padding, borderTopWidth: 0.5, borderTopColor: COLORS.slate, paddingTop: 10, flexDirection: 'row', justifyContent: 'space-between' }} fixed>
        <Text style={{ fontSize: 7, color: '#9CA3AF' }}>GENERATED BY ONFORMAT</Text>
        <Text style={{ fontSize: 7, color: '#9CA3AF' }} render={({ pageNumber, totalPages }) => (
            `${pageNumber} / ${totalPages}`
        )} />
    </View>
);

interface Column {
    header: string;
    accessor: string;
    width: string;
    align?: 'left' | 'right' | 'center';
}

interface DataGridProps {
    columns: Column[];
    data: any[];
}

export const DataGrid = ({ columns, data }: DataGridProps) => {
    return (
        <View style={{ width: '100%', borderTopWidth: 0.5, borderTopColor: COLORS.obsidian }}>
            {/* Header Row */}
            <View style={{ flexDirection: 'row', backgroundColor: COLORS.lightGrey, borderBottomWidth: 0.5, borderBottomColor: COLORS.obsidian, paddingVertical: 6 }} fixed>
                {columns.map((col, i) => (
                    <View key={i} style={{ width: col.width, paddingHorizontal: 4 }}>
                        <Text style={[globalPDFStyles.label, { marginBottom: 0, textAlign: col.align || 'left' }]}>{col.header}</Text>
                    </View>
                ))}
            </View>

            {/* Data Rows */}
            {data.map((row, rowIndex) => (
                <View key={rowIndex} style={{ flexDirection: 'row', borderBottomWidth: 0.5, borderBottomColor: COLORS.slate, paddingVertical: 8 }} wrap={false}>
                    {columns.map((col, colIndex) => (
                        <View key={colIndex} style={{ width: col.width, paddingHorizontal: 4 }}>
                            <Text style={[{ fontSize: 9, textAlign: col.align || 'left' }]}>
                                {row[col.accessor] || ''}
                            </Text>
                        </View>
                    ))}
                </View>
            ))}
        </View>
    );
};
