import React from 'react';
import { Text, View, StyleSheet, Image } from '@react-pdf/renderer';
import { COLORS, LAYOUT, globalStyles } from './PdfTheme';

interface PdfHeaderProps {
    title: string;        // The Document Type (e.g. "CREATIVE BRIEF")
    projectName?: string; // e.g. "PROJECT ALPHA"
    clientName?: string;
    producer?: string;
    date?: string;
}

export const PdfHeader = ({ title, projectName, clientName, producer, date }: PdfHeaderProps) => (
    <View style={{ marginBottom: 24 }} fixed>
        {/* Top Row: Doc Title + QR Code + Date */}
        <View style={{
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'flex-start', // Align to top
            borderBottomWidth: 0.5, // Tactical thin line
            borderBottomColor: COLORS.charcoal,
            paddingBottom: 12,
            marginBottom: 0
        }}>
            {/* Title */}
            <Text style={globalStyles.h1}>{title}</Text>

            {/* Right Side: QR + Date */}
            <View style={{ alignItems: 'flex-end' }}>
                <View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 4 }}>
                    <Text style={{ fontSize: 6, fontWeight: 900, color: COLORS.charcoal, marginRight: 4 }}>GET ONSET MOBILE</Text>
                    <Image
                        src="https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://creative-os.vercel.app/onset"
                        style={{ width: 24, height: 24 }}
                    />
                </View>
                {date && (
                    <Text style={{ fontSize: 9, fontWeight: 700, textTransform: 'uppercase', color: COLORS.mutedText }}>
                        {date}
                    </Text>
                )}
            </View>
        </View>

        {/* Metadata Row: Client/Project + Producer */}
        <View style={{
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingVertical: 8,
            borderBottomWidth: 0.5,
            borderBottomColor: COLORS.slate
        }}>
            {/* Left: Client // Project */}
            <View style={{ flexDirection: 'row', gap: 8 }}>
                {clientName && (
                    <Text style={{ fontSize: 8, fontWeight: 700, textTransform: 'uppercase', color: COLORS.mutedText }}>
                        {clientName} <Text style={{ color: COLORS.slate }}>//</Text>
                    </Text>
                )}
                <Text style={{ fontSize: 8, fontWeight: 700, textTransform: 'uppercase', color: COLORS.obsidian }}>
                    {projectName || 'UNTITLED PROJECT'}
                </Text>
            </View>

            {/* Right: Producer */}
            {producer && (
                <View style={{ flexDirection: 'row', gap: 8 }}>
                    <Text style={{ fontSize: 8, fontWeight: 700, textTransform: 'uppercase', color: COLORS.mutedText }}>
                        PRODUCER
                    </Text>
                    <Text style={{ fontSize: 8, fontWeight: 700, textTransform: 'uppercase', color: COLORS.obsidian }}>
                        {producer}
                    </Text>
                </View>
            )}
        </View>
    </View>
);

export const PdfFooter = () => (
    <View style={{ position: 'absolute', bottom: LAYOUT.padding, left: LAYOUT.padding, right: LAYOUT.padding, borderTopWidth: 1, borderTopColor: COLORS.slate, paddingTop: 10, flexDirection: 'row', justifyContent: 'space-between' }} fixed>
        <Text style={{ fontSize: 7, color: '#9CA3AF' }}>GENERATED BY ONFORMAT</Text>
        <Text style={{ fontSize: 7, color: '#9CA3AF' }} render={({ pageNumber, totalPages }) => (
            `${pageNumber} / ${totalPages}`
        )} />
    </View>
);

interface Column {
    header: string;
    accessor: string; // key in data object
    width: string;    // e.g. '15%'
    align?: 'left' | 'right' | 'center';
}

interface DataGridProps {
    columns: Column[];
    data: any[];
}

export const DataGrid = ({ columns, data }: DataGridProps) => {
    return (
        <View style={{ width: '100%', borderTopWidth: 1, borderTopColor: COLORS.obsidian }}>
            {/* Header Row */}
            <View style={{ flexDirection: 'row', backgroundColor: COLORS.lightGrey, borderBottomWidth: 1, borderBottomColor: COLORS.obsidian, paddingVertical: 6 }} fixed>
                {columns.map((col, i) => (
                    <View key={i} style={{ width: col.width, paddingHorizontal: 4 }}>
                        <Text style={[globalStyles.label, { marginBottom: 0, textAlign: col.align || 'left' }]}>{col.header}</Text>
                    </View>
                ))}
            </View>

            {/* Data Rows */}
            {data.map((row, rowIndex) => (
                <View key={rowIndex} style={{ flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: COLORS.slate, paddingVertical: 8 }} wrap={false}>
                    {columns.map((col, colIndex) => (
                        <View key={colIndex} style={{ width: col.width, paddingHorizontal: 4 }}>
                            <Text style={[{ fontSize: 9, textAlign: col.align || 'left' }]}>
                                {row[col.accessor] || ''}
                            </Text>
                        </View>
                    ))}
                </View>
            ))}
        </View>
    );
};
