import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-black text-zinc-400 font-sans selection:bg-green-500 selection:text-black">
            <nav className="fixed top-0 w-full z-50 px-8 py-6 flex items-center justify-between bg-black/80 backdrop-blur-md border-b border-white/5">
                <Link href="/" className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-white hover:text-green-500 transition-colors">
                    <ArrowLeft size={14} /> Back
                </Link>
                <div className="text-xs font-mono text-zinc-500">LAST UPDATED: JANUARY 14, 2026</div>
            </nav>

            <main className="max-w-3xl mx-auto pt-32 pb-24 px-8">
                <h1 className="text-4xl text-white font-light tracking-wide mb-2">TERMS OF SERVICE</h1>
                <p className="text-sm font-mono text-green-500 mb-12 uppercase tracking-widest">
                    Provided by David Casteel Pictures
                </p>

                <div className="space-y-12 text-sm leading-7">

                    <section>
                        <h3 className="text-white font-bold uppercase tracking-widest mb-4">1. Acceptance of Terms</h3>
                        <p>
                            By accessing and using onFORMAT ("the Service"), you accept and agree to be bound by the terms and provision of this agreement. In addition, when using this Service, you shall be subject to any posted guidelines or rules applicable to such services. Any participation in this service will constitute acceptance of this agreement.
                        </p>
                    </section>

                    <section>
                        <h3 className="text-white font-bold uppercase tracking-widest mb-4">2. Nature of Service</h3>
                        <p>
                            onFORMAT is a productivity and management tool for creative production. The Service is provided tailored for professional use, but <strong>the User bears full responsibility for all production decisions, financial calculations, and safety protocols implemented based on data from the Service.</strong>
                        </p>
                    </section>

                    <section>
                        <h3 className="text-white font-bold uppercase tracking-widest mb-4">3. Limitation of Liability (The "Production Went South" Clause)</h3>
                        <p>
                            TO THE FULLEST EXTENT PERMITTED BY LAW, DAVID CASTEEL PICTURES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, INCURRED EITHER DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.
                        </p>
                        <p className="mt-4">
                            SPECIFICALLY, WE ARE NOT LIABLE FOR:
                        </p>
                        <ul className="list-disc pl-5 mt-2 space-y-2 text-zinc-500">
                            <li><strong>Budget Overruns:</strong> Any financial estimates provided by the AI or templates are for planning purposes only. You are responsible for verifying all costs.</li>
                            <li><strong>Scheduling Errors:</strong> Missed shots, overtime penalties, or logistics failures resulting from reliance on our schedules.</li>
                            <li><strong>On-Set Safety:</strong> Call sheets and risk assessments generated by the platform do not replace the judgment of qualified safety personnel on set.</li>
                        </ul>
                    </section>

                    <section>
                        <h3 className="text-white font-bold uppercase tracking-widest mb-4">4. AI Output Disclaimer</h3>
                        <p>
                            The Service utilizes Artificial Intelligence ("AI Liaison") to generate text, schedules, and budgets. AI is probabilistic and can make mistakes. You acknowledge that any AI-generated content is a suggestion, not professional advice. You must verify all AI outputs before taking action.
                        </p>
                    </section>

                    <section>
                        <h3 className="text-white font-bold uppercase tracking-widest mb-4">5. User Data & Privacy</h3>
                        <p>
                            You retain ownership of all scripts, documents, and production data you upload. We claim no intellectual property rights over the material you provide to the Service. Be aware that while we use industry-standard security (RLS, specialized buckets), no online service can be 100% secure.
                        </p>
                    </section>

                    <section>
                        <h3 className="text-white font-bold uppercase tracking-widest mb-4">6. Termination</h3>
                        <p>
                            We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
                        </p>
                    </section>

                    <section>
                        <h3 className="text-white font-bold uppercase tracking-widest mb-4">7. Governing Law</h3>
                        <p>
                            This Agreement shall be governed in accordance with the laws of the United States and the State of California, without regard to its conflict of law provisions.
                        </p>
                    </section>

                    <div className="pt-12 border-t border-white/10">
                        <p className="text-xs text-zinc-600">
                            Questions? Contact legal@casteelfoto.com<br />
                            © 2026 David Casteel Pictures. All Rights Reserved.
                        </p>
                    </div>

                </div>
            </main>
        </div>
    );
}
