import React from 'react';
import { CheckSquare, Square } from 'lucide-react';
import { TOOLS_BY_PHASE } from '../ExperimentalNav';

export const OnSetControlPanelTemplate = ({ data, onUpdate, isLocked, isPrinting, metadata }: any) => {
    const selectedTools = (data.selectedTools as string[]) || [];

    const toggleTool = (toolKey: string) => {
        if (isLocked) return;
        const newSelection = selectedTools.includes(toolKey)
            ? selectedTools.filter((t: string) => t !== toolKey)
            : [...selectedTools, toolKey];
        onUpdate({ selectedTools: newSelection });
    };

    // Printing / PDF View -> Show Large QR Code Access Sheet
    if (isPrinting) {
        return (
            <div className="flex flex-col items-center justify-center h-full pt-12 text-center bg-white">
                <div className="border-4 border-black p-4 mb-12">
                    <h1 className="text-6xl font-black uppercase tracking-tighter">onSET MOBILE</h1>
                </div>

                <div className="w-96 h-96 bg-black p-4 mb-8">
                    <img
                        src={`https://api.qrserver.com/v1/create-qr-code/?size=500x500&data=https://onformat.io/onset/${metadata?.projectId || 'demo'}`}
                        alt="Scan QR"
                        className="w-full h-full bg-white p-2 object-contain"
                    />
                </div>

                <div className="max-w-md space-y-4">
                    <p className="font-mono text-xl uppercase font-bold tracking-widest text-zinc-900">
                        Scan to access production documents
                    </p>
                    <p className="font-sans text-sm text-zinc-500 uppercase">
                        Project: {metadata?.projectName || 'Untitled'}
                    </p>
                    <div className="pt-8 border-t border-zinc-200 mt-8">
                        <p className="text-[10px] font-mono uppercase text-zinc-400">
                            Generated by onFormat
                        </p>
                    </div>
                </div>
            </div>
        )
    }

    // Editor View -> Control Panel
    return (
        <div className="max-w-4xl mx-auto py-8">
            <div className="flex items-end justify-between mb-8 border-b pb-4">
                <div>
                    <h1 className="text-3xl font-black uppercase tracking-tight mb-2 text-white">onSET Mobile Control</h1>
                    <p className="text-zinc-400 font-mono text-[10px] uppercase tracking-wider">
                        Configure mobile experience & Sync Documents
                    </p>
                </div>
                <div className="text-right flex flex-col items-end gap-4">

                    {/* Live Toggle */}
                    <button
                        onClick={() => onUpdate({ isLive: !data.isLive })}
                        className={`flex items-center gap-2 px-3 py-1.5 rounded-sm text-[10px] font-bold uppercase tracking-widest transition-all
                            ${data.isLive
                                ? 'bg-emerald-500 text-black shadow-[0_0_15px_rgba(16,185,129,0.4)] hover:bg-emerald-400'
                                : 'bg-transparent border border-red-900 text-red-500 hover:bg-red-950 hover:border-red-500 hover:text-red-400'
                            }`}
                    >
                        <div className={`w-1.5 h-1.5 rounded-full ${data.isLive ? 'bg-black animate-pulse' : 'bg-red-500'}`}></div>
                        {data.isLive ? 'LIVE' : 'GO LIVE'}
                    </button>



                    <div className="text-[10px] font-mono text-zinc-500">
                        {selectedTools.length} Documents Selected
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-2 gap-x-12 gap-y-12">
                {/* Phases Loop */}
                {Object.entries(TOOLS_BY_PHASE).map(([phase, tools]) => (
                    <div key={phase} className="mb-2">
                        <h3 className="text-xs font-black uppercase mb-4 text-zinc-300 border-b border-zinc-700 pb-2">{phase.replace('_', ' ')}</h3>
                        <div className="space-y-2">
                            {tools.map((tool: any) => {
                                if (tool.key === 'onset-mobile-control') return null; // Don't show self
                                const isSelected = selectedTools.includes(tool.key);
                                return (
                                    <button
                                        key={tool.key}
                                        onClick={() => toggleTool(tool.key)}
                                        className={`w-full flex items-center justify-between p-2 text-[10px] font-bold uppercase transition-all rounded-sm border ${isSelected ? 'border-zinc-600 bg-zinc-800 text-white' : 'border-transparent text-zinc-500 hover:text-zinc-300 hover:bg-zinc-800/50'}`}
                                    >
                                        <span>{tool.label}</span>
                                        {isSelected ? <CheckSquare size={14} className="text-emerald-500" /> : <Square size={14} className="text-zinc-600" />}
                                    </button>
                                )
                            })}
                        </div>
                    </div>
                ))}
            </div>


        </div>
    );
};
