import React from 'react';
import { CheckSquare, Square } from 'lucide-react';
import { TOOLS_BY_PHASE } from '../ExperimentalNav';

export const OnSetControlPanelTemplate = ({ data, onUpdate, isLocked, isPrinting, metadata }: any) => {
    const selectedTools = (data.selectedTools as string[]) || [];

    const toggleTool = (toolKey: string) => {
        if (isLocked) return;
        const newSelection = selectedTools.includes(toolKey)
            ? selectedTools.filter((t: string) => t !== toolKey)
            : [...selectedTools, toolKey];
        onUpdate({ selectedTools: newSelection });
    };

    // Printing / PDF View -> Show Large QR Code Access Sheet
    if (isPrinting) {
        return (
            <div className="flex flex-col items-center justify-center h-full pt-12 text-center bg-white">
                <div className="border-4 border-black p-4 mb-12">
                    <h1 className="text-6xl font-black uppercase tracking-tighter">onSET MOBILE</h1>
                </div>

                <div className="w-96 h-96 bg-black p-4 mb-8">
                    <img
                        src={`https://api.qrserver.com/v1/create-qr-code/?size=500x500&data=https://onformat.io/onset/${metadata?.projectId || 'demo'}`}
                        alt="Scan QR"
                        className="w-full h-full bg-white p-2 object-contain"
                    />
                </div>

                <div className="max-w-md space-y-4">
                    <p className="font-mono text-xl uppercase font-bold tracking-widest text-zinc-900">
                        Scan to access production documents
                    </p>
                    <p className="font-sans text-sm text-zinc-500 uppercase">
                        Project: {metadata?.projectName || 'Untitled'}
                    </p>
                    <div className="pt-8 border-t border-zinc-200 mt-8">
                        <p className="text-[10px] font-mono uppercase text-zinc-400">
                            Generated by onFormat
                        </p>
                    </div>
                </div>
            </div>
        )
    }

    // Editor View -> Control Panel
    return (
        <div className="max-w-4xl mx-auto py-8">
            <div className="flex items-end justify-between mb-8 border-b pb-4">
                <div>
                    <h1 className="text-3xl font-black uppercase tracking-tight mb-2 text-white">onSET Mobile Control</h1>
                    <p className="text-zinc-400 font-mono text-[10px] uppercase tracking-wider">
                        Configure mobile experience & Sync Documents
                    </p>
                </div>
                <div className="text-right flex flex-col items-end gap-4">

                    {/* Live Toggle */}
                    <button
                        onClick={() => onUpdate({ isLive: !data.isLive })}
                        className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-[10px] font-bold uppercase transition-all ${data.isLive ? 'bg-emerald-500 text-black shadow-[0_0_15px_rgba(16,185,129,0.4)]' : 'bg-zinc-800 text-zinc-500'}`}
                    >
                        <div className={`w-2 h-2 rounded-full ${data.isLive ? 'bg-black animate-pulse' : 'bg-zinc-600'}`}></div>
                        {data.isLive ? 'Production Live' : 'Offline'}
                    </button>

                    {/* Color Picker */}
                    <div className="flex gap-1 bg-zinc-900 p-1 rounded-full border border-zinc-800">
                        {['zinc', 'red', 'blue', 'amber', 'emerald'].map(color => (
                            <button
                                key={color}
                                onClick={() => onUpdate({ themeColor: color })}
                                className={`w-4 h-4 rounded-full transition-transform hover:scale-110 ${data.themeColor === color ? 'ring-2 ring-white scale-110' : 'opacity-50 hover:opacity-100'}
                                ${color === 'zinc' ? 'bg-zinc-500' : ''}
                                ${color === 'red' ? 'bg-red-500' : ''}
                                ${color === 'blue' ? 'bg-blue-500' : ''}
                                ${color === 'amber' ? 'bg-amber-500' : ''}
                                ${color === 'emerald' ? 'bg-emerald-500' : ''}
                                `}
                            />
                        ))}
                    </div>

                    <div className="text-[10px] font-mono text-zinc-500">
                        {selectedTools.length} Documents Selected
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-2 gap-x-12 gap-y-12">
                {/* Phases Loop */}
                {Object.entries(TOOLS_BY_PHASE).map(([phase, tools]) => (
                    <div key={phase} className="mb-2">
                        <h3 className="text-xs font-black uppercase mb-4 text-zinc-300 border-b border-zinc-700 pb-2">{phase.replace('_', ' ')}</h3>
                        <div className="space-y-2">
                            {tools.map((tool: any) => {
                                if (tool.key === 'onset-mobile-control') return null; // Don't show self
                                const isSelected = selectedTools.includes(tool.key);
                                return (
                                    <button
                                        key={tool.key}
                                        onClick={() => toggleTool(tool.key)}
                                        className={`w-full flex items-center justify-between p-2 text-[10px] font-bold uppercase transition-all rounded-sm border ${isSelected ? 'border-zinc-600 bg-zinc-800 text-white' : 'border-transparent text-zinc-500 hover:text-zinc-300 hover:bg-zinc-800/50'}`}
                                    >
                                        <span>{tool.label}</span>
                                        {isSelected ? <CheckSquare size={14} className="text-emerald-500" /> : <Square size={14} className="text-zinc-600" />}
                                    </button>
                                )
                            })}
                        </div>
                    </div>
                ))}
            </div>

            {/* Info Footer */}
            <div className="mt-16 p-6 bg-zinc-900 text-zinc-400 rounded-sm flex items-start gap-6 border border-zinc-800">
                <div className="w-20 h-20 bg-white p-1 shrink-0">
                    <img src="https://api.qrserver.com/v1/create-qr-code/?size=100x100&data=demo" className="w-full h-full opacity-90" alt="Preview QR" />
                </div>
                <div className="flex-1">
                    <h3 className="font-bold uppercase text-xs text-white mb-2">Mobile Access Generation</h3>
                    <p className="text-[10px] leading-relaxed mb-4 font-mono">
                        When ready to distribute to crew, use the "Export PDF" button in the top toolbar.
                        This will generate a dedicated access sheet with a unique QR code.
                        Only the documents selected above will be synchronized to the mobile view.
                    </p>
                    <a
                        href={`/onset/${metadata?.projectId || '#'}`}
                        target="_blank"
                        className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest bg-emerald-500 hover:bg-emerald-400 text-black px-4 py-2 rounded-sm transition-colors"
                    >
                        <span>Launch Mobile Simulator</span>
                        <Square size={12} className="fill-current" />
                    </a>
                </div>
            </div>
        </div>
    );
};
